// Auto-generated version file - do not edit manually
// Generated by Scripts/update_version_from_git.sh

import Foundation

struct GeneratedVersion {
    static let version = "multi-mcp-5c06be7"
    static let buildNumber = "216"
    static let branch = "multi-mcp"
    static let hash = "5c06be7"
}
