#!/bin/bash

# Git-based versioning script
# This script updates Xcode build settings based on git tags and commits

set -euo pipefail

echo "=== Git-based Version Update ==="

# Get git information
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "Git branch: $GIT_BRANCH"

GIT_HASH=$(git rev-parse --short HEAD)
echo "Git hash: $GIT_HASH"

# Create version from branch name and hash
MARKETING_VERSION="${GIT_BRANCH}-${GIT_HASH}"
echo "Marketing version: $MARKETING_VERSION"

# Get total commit count for build number
COMMIT_COUNT=$(git rev-list --count HEAD)
echo "Total commits: $COMMIT_COUNT"

BUILD_NUMBER=$COMMIT_COUNT
echo "Build number: $BUILD_NUMBER"

# Create a version file that the app can read at runtime
VERSION_FILE="HelloWorld/HelloWorld/GeneratedVersion.swift"

echo "Creating $VERSION_FILE..."

cat > "$VERSION_FILE" << EOF
// Auto-generated version file - do not edit manually
// Generated by Scripts/update_version_from_git.sh

import Foundation

struct GeneratedVersion {
    static let version = "$MARKETING_VERSION"
    static let buildNumber = "$BUILD_NUMBER"
    static let branch = "$GIT_BRANCH"
    static let hash = "$GIT_HASH"
}
EOF

echo "✅ Created GeneratedVersion.swift with:"
echo "   Version: $MARKETING_VERSION"
echo "   Build: $BUILD_NUMBER"
echo "   Branch: $GIT_BRANCH"
echo "   Hash: $GIT_HASH"

echo "=== Git versioning complete ==="