// Auto-generated version file - do not edit manually
// Generated by Scripts/update_version_from_git.sh

import Foundation

struct GeneratedVersion {
    static let version = "multi-mcp-eabe196"
    static let buildNumber = "217"
    static let branch = "multi-mcp"
    static let hash = "eabe196"
}
